formulaire front
WildCodeSchool/2023-03-remote-fr-php-huitres-tafforet pull request #15
Opened 2023-04-14 14:34 UTC by ninaschadel

2023-04-17 07:48 UTC, jfm-wcs requested changes
1 petite question sur le css.
Cette feature est donc terminée et prête à être merge...

2023-04-17 07:48 UTC, jfm-wcs commented on public/assets/css/_product_form.css
> +    background-color: var(--primary-inverse);
on est d'accord que le style appliqué sur le h2 de cette page concernera également tous les h2 du site ?

2023-04-17 07:48 UTC, jfm-wcs commented on src/View/Product/product.html.twig
> +		</div>
de manière générale je pense que tu peux mettre les label dans la même div que l'input auxquels ils sont rattachés 😉

2023-04-17 07:48 UTC, jfm-wcs commented on src/View/Product/product.html.twig
> +					<label for="Fines de claires">Fines de claires</label>
il y a un petit souci ici sur les `id` et les `for`. Ce n'est pas possible de mettre plusieurs fois le même `id` (tu as mis `choix` pour chacun des champs). Une solution :
`id="fine-de-claire"` avec `for="fine-de-claire"`, idem pour les autres 😉

2023-04-17 07:48 UTC, jfm-wcs commented on src/View/Product/product.html.twig
> +			<textarea type="textarea" name="commentaire" rows="5"></textarea>
il manque l'`id` ici pour pouvoir être relié à son label.

2023-04-17 07:48 UTC, jfm-wcs commented on src/View/Product/product.html.twig
> +				<label for="Fines de claires">Je souhaite être livré (en supplément)</label>
idem id/for

2023-04-17 07:49 UTC, jfm-wcs reviewed
rapide les changements 😅
d'où ne pas déclencher les PR tant que le travail n'est pas terminé...

2023-04-17 09:05 UTC, ninaschadel commented on public/assets/css/_product_form.css
> +    background-color: var(--primary-inverse);
mince excuse moi JF je viens de voir tous tes commentaires. Je ne savais pas qu'il ne fallait pas push à chaque fois. Je ne ferai que des commit dans ce cas pour mes prochains changements.

2023-04-18 07:48 UTC, jfm-wcs approved these changes

2023-04-18 07:48 UTC, merged