Us 4.3/recipe
WildCodeSchool/2023-03-remote-fr-php-huitres-tafforet pull request #16
Opened 2023-04-15 17:29 UTC by BrianV87

2023-04-17 07:59 UTC, jfm-wcs requested changes
une mini correction et c'est bon 👍

2023-04-17 07:59 UTC, jfm-wcs commented on src/View/Recipe/index.html.twig
> +				<h4>Vins blancs secs et fruités :</h4>
attention, un `<ul>` ne peut avoir que des `<li>` pour descendants 😉

2023-04-17 07:59 UTC, jfm-wcs commented on src/View/Recipe/index.html.twig
> +				<h4>Vins blancs secs et fruités :</h4>
idem h4

2023-04-17 07:59 UTC, jfm-wcs commented on public/assets/css/_recipe-title.css
> +
Tous les h1 du site seront donc en `text-align: center`...

2023-04-17 15:04 UTC, ninaschadel approved these changes

2023-04-18 07:54 UTC, jfm-wcs approved these changes

2023-04-18 07:54 UTC, merged