link bdd and product_card, change name for some image, change css cards
WildCodeSchool/2023-03-remote-fr-php-huitres-tafforet pull request #51
Opened 2023-04-27 08:45 UTC by Karabuff

2023-04-27 09:04 UTC, jfm-wcs requested changes
une mini correction et c'est bon ;)

2023-04-27 09:04 UTC, jfm-wcs commented on src/View/Product/product.html.twig
> +					<h3>{{product.name}}</h3>
idem, ici il faut plutôt mettre du contenu lisible par les lecteurs d'écran, tup eux mettre {{product.name}} ;)

2023-04-27 09:04 UTC, jfm-wcs commented on src/View/Product/product.html.twig
> +				<h3>{{product.name}}</h3>
ici il faut plutôt mettre du contenu lisible par les lecteurs d'écran, tup eux mettre {{product.name}} ;)

2023-04-28 07:59 UTC, BrianV87 approved these changes

2023-04-28 09:05 UTC, jfm-wcs approved these changes
👍

2023-04-28 09:05 UTC, merged